/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duandg;

import Access.CongViecUser;
import Access.DacTinhCaNhanUser;
import Access.GiaDinhUser;
import Access.HocVanUser;
import Access.ThongTinCaNhanDAO;
import Access.ThongTinKhacUser;
import Access.TinhTrangSucKhoeUser;
import Service.UserService;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ThongTinCaNhan;

/**
 *
 * @author Nhat Anh
 */
public class danhsach extends javax.swing.JFrame {
    UserService userService;
    /**
     * Creates new form danhsach
     */
    DefaultTableModel defaultTableModel;
    public danhsach() {
        initComponents();
        userService = new UserService();
        defaultTableModel = new DefaultTableModel();
        danhsachtt.setModel(defaultTableModel); 
        
        defaultTableModel.addColumn("Họ Tên");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Tôn Giáo");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Tuổi");
        defaultTableModel.addColumn("Nơi Sinh");
        defaultTableModel.addColumn("Nguyên Quán");
        defaultTableModel.addColumn("Dân Tộc");
        defaultTableModel.addColumn("Hôn Nhân");
        defaultTableModel.addColumn("CMND");
        defaultTableModel.addColumn("Ngày cấp cmnd");
        defaultTableModel.addColumn("Nơi cấp cmnd");
        defaultTableModel.addColumn("Passport");
        defaultTableModel.addColumn("Ngày Cấp pp");
        defaultTableModel.addColumn("Nơi cấp pp");
        defaultTableModel.addColumn("Hộ khẩu");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("Địa chỉ ll");
        defaultTableModel.addColumn("SĐTLL");
        defaultTableModel.addColumn("Họ tên ll");
        defaultTableModel.addColumn("Mối quan hệ");
        getds();
    }
    private void getds(){
    
        ThongTinCaNhanDAO tt=new ThongTinCaNhanDAO();
        List<ThongTinCaNhan> thongtincanhans = tt.getAllUsers();
        defaultTableModel.setRowCount(0);
        for (ThongTinCaNhan thongtincanhan : thongtincanhans){
            defaultTableModel.addRow(new Object[]{thongtincanhan.getHoten(),thongtincanhan.getGioitinh(),thongtincanhan.getTongiao(),thongtincanhan.getNgaysinh(),thongtincanhan.getTuoi(),
                thongtincanhan.getNoisinh(),thongtincanhan.getNguyenquan(),thongtincanhan.getDantoc(),thongtincanhan.getHonnhan(),thongtincanhan.getCmnd(),thongtincanhan.getNgaycapcc(),
                thongtincanhan.getNoicapcc(),thongtincanhan.getPassport(),thongtincanhan.getNgaycappp(),thongtincanhan.getNoicappp(),thongtincanhan.getHokhau(),thongtincanhan.getSdt(),
                thongtincanhan.getDiachill(),thongtincanhan.getSdtll(),thongtincanhan.getHotenll(),thongtincanhan.getMqh(),});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        danhsachtt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcmnd = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jThoat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        JInBang = new javax.swing.JButton();
        jInDKLV = new javax.swing.JButton();
        jinckdt = new javax.swing.JButton();
        jThemEx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        danhsachtt.setAutoCreateRowSorter(true);
        danhsachtt.setBorder(new javax.swing.border.MatteBorder(null));
        danhsachtt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Họ Tên", "Giới tính", "Tôn giáo", "Ngày sinh", "Tuổi", "Nơi sinh", "Nguyên quán", "Dân tộc ", "Hôn nhân", "CMND/CCCD", "Ngày cấp CM/CC", "Nơi cấp CM/CC", "Passport", "Ngày cấp pp", "Nơi cấp pp", "Hộ khẩu", "SĐT", "Địa chỉ LL", "SĐT LL", "Họ tên LL", "Mối quan hệ"
            }
        ));
        danhsachtt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        danhsachtt.setGridColor(new java.awt.Color(255, 255, 255));
        danhsachtt.setRowHeight(30);
        danhsachtt.setSelectionBackground(new java.awt.Color(255, 153, 102));
        danhsachtt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        danhsachtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhsachttMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(danhsachtt);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(237, 88, 68));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 88, 68));
        jLabel5.setText("DGNZM PRINT");

        txtcmnd.setEnabled(false);
        txtcmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcmndActionPerformed(evt);
            }
        });

        txtTen.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CMND");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Họ Và Tên");

        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        jSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSearchKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-01 (1).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Webp.net-resizeimage (2).png"))); // NOI18N

        jThoat.setBackground(new java.awt.Color(255, 255, 255));
        jThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jThoat.setForeground(new java.awt.Color(204, 0, 0));
        jThoat.setText("Thoát");
        jThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThoatActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText(" Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcmnd, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addComponent(jSearch))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jThoat))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jThoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(237, 88, 68));

        jButton2.setText("syll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        JInBang.setBackground(new java.awt.Color(255, 255, 255));
        JInBang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JInBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paper.png"))); // NOI18N
        JInBang.setText("In bảng tự thuật");
        JInBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JInBangActionPerformed(evt);
            }
        });
        jPanel1.add(JInBang);

        jInDKLV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jInDKLV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paper.png"))); // NOI18N
        jInDKLV.setText("In Đơn Đăng Ký Làm Việc");
        jInDKLV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInDKLVActionPerformed(evt);
            }
        });
        jPanel1.add(jInDKLV);

        jinckdt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jinckdt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/paper.png"))); // NOI18N
        jinckdt.setText("In Đơn Cam Kết Dự Tuyển");
        jinckdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinckdtActionPerformed(evt);
            }
        });
        jPanel1.add(jinckdt);

        jThemEx.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jThemEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel.png"))); // NOI18N
        jThemEx.setText("Thêm excel");
        jThemEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThemExActionPerformed(evt);
            }
        });
        jPanel1.add(jThemEx);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JInBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JInBangActionPerformed
        // TODO add your handling code here:
        if(txtcmnd.getText().length()<=0){JOptionPane.showMessageDialog(this, "Vui lòng chọn người cần in"); return;}
        Print_Form form=new Print_Form(txtcmnd.getText().toString().trim());
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JInBangActionPerformed

    private void danhsachttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhsachttMouseClicked
        // TODO add your handling code here:
        int row=danhsachtt.getSelectedRow();
        if(row!=-1){
            txtcmnd.setText((String)danhsachtt.getValueAt(row, 9));
            txtTen.setText((String)danhsachtt.getValueAt(row, 0));
        }
    }//GEN-LAST:event_danhsachttMouseClicked

    private void jThemExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThemExActionPerformed
        // TODO add your handling code here:
        this.dispose();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int rs=chooser.showSaveDialog(null);
        if(rs==JFileChooser.APPROVE_OPTION){
            String path=chooser.getSelectedFile().getAbsolutePath();
            String filename=chooser.getSelectedFile().getName();
            System.out.println(filename);
            if(filename.contains(".xlsx")){
            try {
            
            new CongViecUser().readFile(path);
            new DacTinhCaNhanUser().readFile(path);
            new GiaDinhUser().readFile(path);
            new HocVanUser().readFile(path);
            new ThongTinCaNhanDAO().readFile(path);
            new ThongTinKhacUser().readFile(path);
            new TinhTrangSucKhoeUser().readFile(path);
            
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            
            } catch (IOException ex) {
                Logger.getLogger(danhsach.class.getName()).log(Level.SEVERE, null, ex);

            }}else JOptionPane.showMessageDialog(this, "Sai đường dẫn");
             
        }
        else {
            JOptionPane.showMessageDialog(this, "that bai");
            new danhsach().setVisible(true);
                return;
        }
        
        new danhsach().setVisible(true);
    }//GEN-LAST:event_jThemExActionPerformed

    private void jThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThoatActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jThoatActionPerformed
   
    private void jInDKLVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInDKLVActionPerformed
        // TODO add your handling code here:
        if(txtcmnd.getText().length()<=0){JOptionPane.showMessageDialog(this, "Vui lòng chọn người cần in"); return;}
        FormDKLVC form=new FormDKLVC(txtcmnd.getText().toString().trim());
        form.setVisible(true);
//        this.setVisible(false);
this.dispose();
    }//GEN-LAST:event_jInDKLVActionPerformed

    private void jinckdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinckdtActionPerformed
        if(txtcmnd.getText().length()<=0){JOptionPane.showMessageDialog(this, "Vui lòng chọn người cần in"); return;}
        FormCKDT form1=new FormCKDT(txtcmnd.getText().toString().trim());
        form1.setVisible(true);this.dispose();
//        this.setVisible(false);
    }//GEN-LAST:event_jinckdtActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jSearchActionPerformed

    private void jSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jSearchKeyPressed

    private void jSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchKeyReleased
        // TODO add your handling code here:
//        DefaultTableModel table = (DefaultTableModel)danhsachtt.getModel();
//        String search = jSearch.getText().toLowerCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
//        danhsachtt.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jSearchKeyReleased

    private void txtcmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcmndActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jSearch.getText()=="") getds();
        else{
            ThongTinCaNhanDAO tt=new ThongTinCaNhanDAO();
        List<ThongTinCaNhan> thongtincanhans = tt.getAllUsersByName(jSearch.getText());
        defaultTableModel.setRowCount(0);
        for (ThongTinCaNhan thongtincanhan : thongtincanhans){
            defaultTableModel.addRow(new Object[]{thongtincanhan.getHoten(),thongtincanhan.getGioitinh(),thongtincanhan.getTongiao(),thongtincanhan.getNgaysinh(),thongtincanhan.getTuoi(),
                thongtincanhan.getNoisinh(),thongtincanhan.getNguyenquan(),thongtincanhan.getDantoc(),thongtincanhan.getHonnhan(),thongtincanhan.getCmnd(),thongtincanhan.getNgaycapcc(),
                thongtincanhan.getNoicapcc(),thongtincanhan.getPassport(),thongtincanhan.getNgaycappp(),thongtincanhan.getNoicappp(),thongtincanhan.getHokhau(),thongtincanhan.getSdt(),
                thongtincanhan.getDiachill(),thongtincanhan.getSdtll(),thongtincanhan.getHotenll(),thongtincanhan.getMqh(),});
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txtcmnd.getText().length()<=0){JOptionPane.showMessageDialog(this, "Vui lòng chọn người cần in"); return;}
        Form_SYLL form1=new Form_SYLL(txtcmnd.getText().toString().trim());
        form1.setVisible(true);this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(danhsach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new danhsach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JInBang;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JTable danhsachtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jInDKLV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearch;
    private javax.swing.JButton jThemEx;
    private javax.swing.JButton jThoat;
    private javax.swing.JButton jinckdt;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtcmnd;
    // End of variables declaration//GEN-END:variables
}
