/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duandg;

import Access.ThongTinCaNhanDAO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.ThongTinCaNhan;

/**
 *
 * @author Nhat Anh
 */
public class FormDKLVC extends javax.swing.JFrame {
     
     ThongTinCaNhanDAO ttcn;
     
     private void getdl(){
       ttcn=new ThongTinCaNhanDAO();
       ThongTinCaNhan thongtin= ttcn.getUsers(cmnd);
       
       jhoten.setText(thongtin.getHoten());
       jnoisinh.setText(thongtin.getNoisinh());
       jgioitinh.setText(thongtin.getGioitinh());      
       jngaysinh.setText(thongtin.getNgaysinh());
       jsocmnd.setText(thongtin.getCmnd());
       jnoicapcc.setText(thongtin.getNgaycapcc());
       jnoicapcc.setText(thongtin.getNoicapcc());
       
       jhokhau.setText(thongtin.getHokhau());
       jdiachi.setText(thongtin.getDiachill());
       jsdt.setText(thongtin.getSdt());
       jhochieu.setText(thongtin.getPassport());
       jngaycaphc.setText(thongtin.getNgaycappp());
        
     }
    /**
     * Creates new form FormDKLVC
     */
    public FormDKLVC() {
        initComponents();
    }
    private String cmnd;
    public FormDKLVC(String cmnd) {
        initComponents();
        this.cmnd=cmnd;
        getdl();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jngaysinh = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jnoisinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jsocmnd = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jhochieu = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jngaycaphc = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jdiachi = new javax.swing.JLabel();
        jtxt = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jhokhau = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jhoten = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jgioitinh = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jnoicapcc = new javax.swing.JLabel();
        jsdt = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt11 = new javax.swing.JLabel();
        jtxt12 = new javax.swing.JLabel();
        jtxt13 = new javax.swing.JLabel();
        jtxt14 = new javax.swing.JLabel();
        jtxt15 = new javax.swing.JLabel();
        jtxt16 = new javax.swing.JLabel();
        jtxt17 = new javax.swing.JLabel();
        jtxt18 = new javax.swing.JLabel();
        jtxt19 = new javax.swing.JLabel();
        jtxt20 = new javax.swing.JLabel();
        jtxt21 = new javax.swing.JLabel();
        jngaycapcc2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        tuychon = new javax.swing.JMenu();
        printRecord = new javax.swing.JMenuItem();
        QL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐƠN ĐĂNG KÝ ĐI LÀM VIỆC Ở NƯỚC NGOÀI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1120, 60));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel10.setText("-  Họ và tên:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jngaysinh.setText("30062000");
        jPanel2.add(jngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 230, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel14.setText("Nơi sinh:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        jnoisinh.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jnoisinh.setText("daklak");
        jPanel2.add(jnoisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 304, 570, 30));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel16.setText("-  Hộ khẩu thường trú:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jsocmnd.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jsocmnd.setText("123456789122");
        jPanel2.add(jsocmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 200, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel22.setText("-  CMND/CCCD:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jhochieu.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jhochieu.setText("123456789");
        jPanel2.add(jhochieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 260, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel24.setText("Ngày cấp:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jngaycaphc.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jngaycaphc.setText("30/06/2000");
        jPanel2.add(jngaycaphc, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 170, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel26.setText("-  Địa chỉ liên lạc:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel28.setText("-  Số hộ chiếu (nếu có):");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jdiachi.setFont(new java.awt.Font("Times New Roman", 0, 27)); // NOI18N
        jdiachi.setText("1234567891011");
        jPanel2.add(jdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 1150, -1));

        jtxt.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt.setText("tham gia chương trình đi lao động có thời hạn ở nước ngoài mà công ty đang tiến hành.");
        jPanel2.add(jtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1230, 1130, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel32.setText("Nơi cấp:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        jhokhau.setFont(new java.awt.Font("Times New Roman", 0, 27)); // NOI18N
        jhokhau.setText("daklak, phuong abc, so nha. tinh thanh pho noi o abc xzy 1/100/100/111");
        jPanel2.add(jhokhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1150, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel36.setText("-  Số điện thoại:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel4.setText("-  Ngày, tháng, năm sinh:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jhoten.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jhoten.setText("NTNA");
        jPanel2.add(jhoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 520, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel6.setText("Giới tính:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        jgioitinh.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jgioitinh.setText("Nam");
        jPanel2.add(jgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 210, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel25.setText("Ngày cấp:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jnoicapcc.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jnoicapcc.setText("Tỉnh Bà Rịa - Vũng Tàu");
        jPanel2.add(jnoicapcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 310, -1));

        jsdt.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jsdt.setText("30062000");
        jPanel2.add(jsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 190, -1));

        jLabel204.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel204.setText("(Ký và ghi rõ họ tên)");
        jPanel2.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1340, -1, -1));

        jLabel218.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel218.setText(".............Ngày............Tháng.........Năm.........");
        jPanel2.add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1300, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/testfoot4.png"))); // NOI18N
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KeyChinh.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        jtxt11.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt11.setText("Sau khi được tư vấn và đã tìm hiểu rõ các vấn đề liên quan đến chương trình đi làm việc");
        jPanel2.add(jtxt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 1090, -1));

        jtxt12.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt12.setText("ở nước ngoài, tôi nhận thấy hoàn toàn có đầy đủ khả năng để tham gia nên tôi tự nguyện");
        jPanel2.add(jtxt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 1090, -1));

        jtxt13.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt13.setText("làm đơn này xin được đi làm việc ở nước ngoài thông qua sự phái cử của Quý Công ty, nếu");
        jPanel2.add(jtxt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 1090, -1));

        jtxt14.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt14.setText("được chấp thuận tôi xin cam kết:");
        jPanel2.add(jtxt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 1090, -1));

        jtxt15.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt15.setText("-  Bản thân tôi tự tìm hiểu và tự đến đăng ký trực tiếp tại công ty DŨNG GIANG.");
        jPanel2.add(jtxt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 880, 1090, -1));

        jtxt16.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt16.setText("-  Nội dung khai báo ở trên và trong phiếu sơ vấn là đầy đủ rõ ràng và chính xác.");
        jPanel2.add(jtxt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 930, 1090, -1));

        jtxt17.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt17.setText("-  Thực hiện đúng các qui trình thủ tục về hồ sơ, tuyển chọn của công ty DŨNG GIANG.");
        jPanel2.add(jtxt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 980, 1090, -1));

        jtxt18.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt18.setText("Đảm bảo khai đúng lý lịch, sức khỏe và đảm bảo tính xác thực của các hồ sơ cá nhân đã ");
        jPanel2.add(jtxt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, 1130, -1));

        jtxt19.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt19.setText("nộp và có trách nhiệm phải khai báo bổ sung những nội dung thay đổi (nếu có) trong suốt");
        jPanel2.add(jtxt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1080, 1130, -1));

        jtxt20.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt20.setText("quá trình thực hiện chương trình thực tập sinh.");
        jPanel2.add(jtxt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1130, 1130, -1));

        jtxt21.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jtxt21.setText("   Đề nghị công ty DŨNG GIANG cho phép tôi tiến hành các thủ tục cần thiết để dự tuyển");
        jPanel2.add(jtxt21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1180, 1130, -1));

        jngaycapcc2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jngaycapcc2.setText("30/06/2000");
        jPanel2.add(jngaycapcc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 1660));

        tuychon.setText("Tùy chọn");
        tuychon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuychonActionPerformed(evt);
            }
        });

        printRecord.setText("In File ");
        printRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRecordActionPerformed(evt);
            }
        });
        tuychon.add(printRecord);

        QL.setText("Quay lại");
        QL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLActionPerformed(evt);
            }
        });
        tuychon.add(QL);

        jMenuBar1.add(tuychon);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1208, 1732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRecordActionPerformed
        // TODO add your handling code here:
        PrintUtil p=new PrintUtil(jPanel2);
        p.print();
    }//GEN-LAST:event_printRecordActionPerformed

    private void QLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLActionPerformed
        danhsach ds = new danhsach();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_QLActionPerformed

    private void tuychonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuychonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tuychonActionPerformed

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
          int h = jPanel2.getHeight();
        int a = evt.getWheelRotation();
        int x = jPanel2.getX();
        int y = jPanel2.getY();
        int b = 0;
        if(a>0)
        {
            if(y==this.getHeight()-jPanel2.getHeight())
            {
                a=0;
            }else
            {
                b+=50;
                jPanel2.setLocation(x,y-b);
                b=0;
            }
        }
        if(a<0)
        {
            if(y==0)
            {
                a=0;
            }else
            {
                b+=50;
                jPanel2.setLocation(x,y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         new danhsach().setVisible(true);
        setDefaultCloseOperation(FormDKLVC.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDKLVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDKLVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDKLVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDKLVC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDKLVC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem QL;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jdiachi;
    private javax.swing.JLabel jgioitinh;
    private javax.swing.JLabel jhochieu;
    private javax.swing.JLabel jhokhau;
    private javax.swing.JLabel jhoten;
    private javax.swing.JLabel jngaycapcc2;
    private javax.swing.JLabel jngaycaphc;
    private javax.swing.JLabel jngaysinh;
    private javax.swing.JLabel jnoicapcc;
    private javax.swing.JLabel jnoisinh;
    private javax.swing.JLabel jsdt;
    private javax.swing.JLabel jsocmnd;
    private javax.swing.JLabel jtxt;
    private javax.swing.JLabel jtxt11;
    private javax.swing.JLabel jtxt12;
    private javax.swing.JLabel jtxt13;
    private javax.swing.JLabel jtxt14;
    private javax.swing.JLabel jtxt15;
    private javax.swing.JLabel jtxt16;
    private javax.swing.JLabel jtxt17;
    private javax.swing.JLabel jtxt18;
    private javax.swing.JLabel jtxt19;
    private javax.swing.JLabel jtxt20;
    private javax.swing.JLabel jtxt21;
    private javax.swing.JMenuItem printRecord;
    private javax.swing.JMenu tuychon;
    // End of variables declaration//GEN-END:variables

    private int printRecord(JPanel panel){
        
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D graphics2D =(Graphics2D)graphics;
                
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                
                graphics2D.scale(0.5,0.5);
                
                panel.print(graphics2D);
                
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        int t=0;
        if(returningResult){
            try{
                printerJob.print();
                return t=1;
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "In Lỗi :" + printerException.getLocalizedMessage());
            }
        }
        return t;
    }
}

