/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duandg;

import Access.CongViecUser;
import Access.ThongTinCaNhanDAO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.CongViec;
import model.ThongTinCaNhan;

/**
 *
 * @author Nhat Anh
 */
public class FormCKDT extends javax.swing.JFrame {

    ThongTinCaNhanDAO ttcn;
    CongViecUser cv; 
   
    private void congviec(List<CongViec> l){
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        
        defaultTableModel.addColumn("Từ tháng/năm");
        defaultTableModel.addColumn("Đến tháng/năm");
        defaultTableModel.addColumn("Tên Công Ty");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("Công Việc");
        defaultTableModel.addColumn("Lương");
        for(CongViec hv:l){
             defaultTableModel.addRow(new Object[]{hv.getCongviec()});
        }
    }
    
     private void getdl(){
       cv= new CongViecUser();
       ttcn=new ThongTinCaNhanDAO();
       ThongTinCaNhan thongtin= ttcn.getUsers(cmnd);
        List<CongViec> listcv= cv.getAllUsers(cmnd);
        String cv="";
        for(CongViec c:listcv){
            cv+=c.getCongviec()+". ";
        }
        jnghenghiep.setText(cv);
        jhoten.setText(thongtin.getHoten());
        jngaysinh.setText(thongtin.getNgaysinh());
        jsocmnd.setText(thongtin.getCmnd());
        jngaycapcc1.setText(thongtin.getNgaycapcc());
        jnoicapcc.setText(thongtin.getNoicapcc());
        jhokhau.setText(thongtin.getHokhau());
        
     }
    
    /**
     * Creates new form FormCKDT
     */
    public FormCKDT() {
        initComponents();
    }
    private String cmnd;
    public FormCKDT(String cmnd) {
        initComponents();
        this.cmnd=cmnd;
        getdl();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jngaysinh = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jsocmnd = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jnghenghiep = new javax.swing.JLabel();
        jnoicapcc = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtxt = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jhokhau = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jhoten = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jngaycapcc1 = new javax.swing.JLabel();
        jtxt1 = new javax.swing.JLabel();
        jtxt2 = new javax.swing.JLabel();
        jtxt3 = new javax.swing.JLabel();
        jtxt4 = new javax.swing.JLabel();
        jtxt5 = new javax.swing.JLabel();
        jtxt6 = new javax.swing.JLabel();
        jtxt7 = new javax.swing.JLabel();
        jtxt8 = new javax.swing.JLabel();
        jtxt9 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        jLabel218 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt10 = new javax.swing.JLabel();
        jtxt11 = new javax.swing.JLabel();
        jtxt12 = new javax.swing.JLabel();
        jtxt13 = new javax.swing.JLabel();
        jtxt14 = new javax.swing.JLabel();
        jtxt15 = new javax.swing.JLabel();
        jtxt16 = new javax.swing.JLabel();
        jtxt18 = new javax.swing.JLabel();
        jtxt19 = new javax.swing.JLabel();
        jtxt20 = new javax.swing.JLabel();
        jtxt22 = new javax.swing.JLabel();
        jtxt23 = new javax.swing.JLabel();
        jtxt24 = new javax.swing.JLabel();
        jtxt25 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jtxt26 = new javax.swing.JLabel();
        jtxt27 = new javax.swing.JLabel();
        jtxt28 = new javax.swing.JLabel();
        jtxt29 = new javax.swing.JLabel();
        jtxt30 = new javax.swing.JLabel();
        jtxt31 = new javax.swing.JLabel();
        jtxt32 = new javax.swing.JLabel();
        jtxt33 = new javax.swing.JLabel();
        jtxt34 = new javax.swing.JLabel();
        jtxt35 = new javax.swing.JLabel();
        jtxt36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        tuychon = new javax.swing.JMenu();
        printRecord = new javax.swing.JMenuItem();
        QL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 25)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("V/v : Đăng ký dự tuyển và làm thủ tục đi thực tập ở nước ngoài");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1120, 40));

        jngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jngaysinh.setText("30062000");
        jPanel2.add(jngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 130, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel16.setText("Địa chỉ thường trú:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jsocmnd.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jsocmnd.setText("123456789");
        jPanel2.add(jsocmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 210, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel22.setText("Số CMND:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jnghenghiep.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jnghenghiep.setText("123456789");
        jPanel2.add(jnghenghiep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 940, -1));

        jnoicapcc.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jnoicapcc.setText("daklak");
        jPanel2.add(jnoicapcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 520, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel28.setText("Nghề nghiệp:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jtxt.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt.setText("Sau khi tìm hiểu rõ các tiêu chuẩn, điều kiện và quy trình tuyển chọn của công ty DŨNG GIANG, bản thân tôi thấy có đủ khả năng");
        jPanel2.add(jtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 1070, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel32.setText("Nơi cấp:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jhokhau.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jhokhau.setText("daklak, phuong abc, so nha. tinh thanh pho noi o abc xzy 1/100/100/111");
        jPanel2.add(jhokhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 960, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel4.setText(" Ngày sinh:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jhoten.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jhoten.setText("NTNA");
        jPanel2.add(jhoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 190, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel25.setText("Ngày cấp:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jngaycapcc1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jngaycapcc1.setText("30/06/2000");
        jPanel2.add(jngaycapcc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 120, -1));

        jtxt1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt1.setText("tài chính và chấp nhận chi phí như đã thỏa thuận.");
        jPanel2.add(jtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 1120, -1));

        jtxt2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt2.setText("cọc dự phỏng vấn.");
        jPanel2.add(jtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 920, 1160, -1));

        jtxt3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt3.setText("Tôi quyết định tham dự tuyển chọn và làm các thủ tục liên quan theo sự hướng dẫn của công ty.");
        jPanel2.add(jtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 1090, -1));

        jtxt4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt4.setText("Tôi xin cam kết:");
        jPanel2.add(jtxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 1090, -1));

        jtxt5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt5.setText("B.");
        jPanel2.add(jtxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 30, 60));

        jtxt6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt6.setText("Thực hiện đúng quy trình tuyển chọn của công ty, tự chịu các chi phí để dự tuyển như: lệ phí đăng ký; làm hồ sơ cá nhân; làm thủ ");
        jPanel2.add(jtxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 1100, -1));

        jtxt7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt7.setText("tục bảo lãnh tại ngân hàng (nếu có yêu cầu); phí khám sức khỏe; phí học bồi dưỡng nghề (nếu có); chi phí đi lại, ăn ở để dự tuyển và  ");
        jPanel2.add(jtxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 1120, -1));

        jtxt8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt8.setText("và tiền học trước khi đi (đối với hợp đồng phía nước ngoài không tài trợ tiền học).");
        jPanel2.add(jtxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 1120, -1));

        jtxt9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt9.setText("Tôi sẽ không đòi bồi thường hoặc đòi lại các chi phí nói trên trong các trường hợp sau đây:");
        jPanel2.add(jtxt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 1120, -1));

        jLabel204.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel204.setText("(Ký và ghi rõ họ tên)");
        jPanel2.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1370, -1, -1));

        jLabel218.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel218.setText(".............Ngày............Tháng.........Năm.........");
        jPanel2.add(jLabel218, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel11.setText("Tôi tên:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CAM KẾT DỰ TUYỂN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1120, 60));

        jtxt10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt10.setText("1. Tự ý bỏ giữa chừng vì lý do cá nhân.");
        jPanel2.add(jtxt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 1120, -1));

        jtxt11.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt11.setText("2. Không đủ sức khỏe.");
        jPanel2.add(jtxt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, 1120, -1));

        jtxt12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt12.setText("3. Trục trặc về giấy tờ, lý lịch cá nhân, nước tiếp nhận không cấp VISA.");
        jPanel2.add(jtxt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, 1120, -1));

        jtxt13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt13.setText("4. Kết quả học tiếng Nhật không đạt yêu cầu hoặc tư cách đạo đức, tác phong lao động và ý thức tổ chức lỷ luật kém trong thời gian");
        jPanel2.add(jtxt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, 1120, -1));

        jtxt14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt14.setText(" học trước khi đi nên bị hủy bỏ.");
        jPanel2.add(jtxt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 820, 1120, -1));

        jtxt15.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jPanel2.add(jtxt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1020, 1120, -1));

        jtxt16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt16.setText("Trong trường hợp đã được xếp và ký tên vào danh sách phỏng vấn, nếu tôi tự ý bỏ không đếm tham dự phỏng vấn như đã thông báo,  ");
        jPanel2.add(jtxt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 860, 1120, -1));

        jtxt18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt18.setText("Trong trường hợp tôi không trúng tuyển hoặc phía đối tác đơn phương hủy bỏ phỏng vấn, tôi đồng ý  chỉ nhận lại số tiền 5.000.000");
        jPanel2.add(jtxt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 960, 1120, -1));

        jtxt19.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt19.setText("Khi được trúng tuyển và trong thời gian học tiếng Nhật, làm thủ tục để đi, tôi cam kết tuân thủ đúng  theo các qui định,yêu cầu của ");
        jPanel2.add(jtxt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1030, 1120, 20));

        jtxt20.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt20.setText("công ty, nghiêm chỉnh chấp hành nội qui khóa đào tạo. Nếu tôi tự ý bỏ vì  các lý do cá nhân, tôi sẽ không được lấy lạisố tiền đặt cọc ");
        jPanel2.add(jtxt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1060, 1140, 20));

        jtxt22.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt22.setText("Về việc khai báo lý lịch cá nhân tôi xin cam kết là chính xác và đầy đủ, chưa lần nào đi tu nghiệp hoặc làm việc trên bộ cũng như ");
        jPanel2.add(jtxt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1130, 1140, 20));

        jtxt23.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt23.setText("trên các tàu, thuyền của Nhật Bản. Nếu cố tình khai man, che dấu sự việc trên dẫn đến bị hủy tư cách thực tập sinh,tôi cam kết chịu mọi ");
        jPanel2.add(jtxt23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1160, 1140, 20));

        jtxt24.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt24.setText("hình thức kỷ luật, chấp nhận đóng phạt và chi  trả tất cả các chi phí phát sinh khác. ");
        jPanel2.add(jtxt24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1190, 1140, 20));

        jtxt25.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt25.setText("Tôi sẽ không khiếu kiện đòi bồi thường hoặc có hành vi gây rối.");
        jPanel2.add(jtxt25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1260, -1, 20));

        jLabel205.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel205.setText("Người cam kết");
        jPanel2.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 1340, -1, -1));

        jtxt26.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt26.setText("hoặc nếu tôi đã phỏng vấn trúng truyển nhưng tự ý không tiếp tục tham gia chương trình tôi chấp nhận bị trừ 5.000.000 đồng từ tiền đặt ");
        jPanel2.add(jtxt26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 890, 1160, -1));

        jtxt27.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt27.setText("dự phỏng vấn và sẽ bị phạt số tiền tương  đương 500 USD để công ty chi phí vào việc tuyển chọn và làm lại thủ tục cho người thay thế.");
        jPanel2.add(jtxt27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1090, 1140, 20));

        jtxt28.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt28.setText(" đồng sau khi trừ chi phí bồi dưỡng và sát hạch nghề (nếu  có) hoặc xin bảo lưu chờ dự tuyển đợt khác.");
        jPanel2.add(jtxt28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 990, 1120, -1));

        jtxt29.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt29.setText("Tôi trực tiếp đến đăng ký và làm thủ tục dự tuyển tại văn phòng công ty DŨNG GIANG.");
        jPanel2.add(jtxt29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 1090, -1));

        jtxt30.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt30.setText("C.");
        jPanel2.add(jtxt30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 20, -1));

        jtxt31.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt31.setText("A.");
        jPanel2.add(jtxt31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 20, -1));

        jtxt32.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt32.setText("G.");
        jPanel2.add(jtxt32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1130, 30, 20));

        jtxt33.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt33.setText("D.");
        jPanel2.add(jtxt33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 860, 20, -1));

        jtxt34.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt34.setText("E.");
        jPanel2.add(jtxt34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, 20, -1));

        jtxt35.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jtxt35.setText("F.");
        jPanel2.add(jtxt35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1030, 20, 20));

        jtxt36.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jtxt36.setText("Tôi tự nguyện làm tờ cam kết này. Tôi đã đọc kỹ, hiểu rõ và sẽ thực hiện đúng những cam kết nói trên.");
        jPanel2.add(jtxt36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1230, -1, 20));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/testfoot4.png"))); // NOI18N
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lg.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KeyChinh.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 1680));

        tuychon.setText("Tùy chọn");
        tuychon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuychonActionPerformed(evt);
            }
        });

        printRecord.setText("In File ");
        printRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printRecordActionPerformed(evt);
            }
        });
        tuychon.add(printRecord);

        QL.setText("Quay lại");
        QL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLActionPerformed(evt);
            }
        });
        tuychon.add(QL);

        jMenuBar1.add(tuychon);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
        int h = jPanel2.getHeight();
        int a = evt.getWheelRotation();
        int x = jPanel2.getX();
        int y = jPanel2.getY();
        int b = 0;
        if(a>0)
        {
            if(y==this.getHeight()-jPanel2.getHeight())
            {
                a=0;
            }else
            {
                b+=50;
                jPanel2.setLocation(x,y-b);
                b=0;
            }
        }
        if(a<0)
        {
            if(y==0)
            {
                a=0;
            }else
            {
                b+=50;
                jPanel2.setLocation(x,y+b);
                b=0;
            }
        }
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    private void printRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printRecordActionPerformed
        // TODO add your handling code here:
        PrintUtil p=new PrintUtil(jPanel2);
        p.print();
    }//GEN-LAST:event_printRecordActionPerformed

    private void QLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLActionPerformed
        danhsach ds = new danhsach();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_QLActionPerformed

    private void tuychonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuychonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuychonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
     setDefaultCloseOperation(FormCKDT.DISPOSE_ON_CLOSE); 
     
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here: // TODO add your handling code here:
        new danhsach().setVisible(true);
       setDefaultCloseOperation(FormCKDT.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCKDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCKDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCKDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCKDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCKDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem QL;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel218;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jhokhau;
    private javax.swing.JLabel jhoten;
    private javax.swing.JLabel jngaycapcc1;
    private javax.swing.JLabel jngaysinh;
    private javax.swing.JLabel jnghenghiep;
    private javax.swing.JLabel jnoicapcc;
    private javax.swing.JLabel jsocmnd;
    private javax.swing.JLabel jtxt;
    private javax.swing.JLabel jtxt1;
    private javax.swing.JLabel jtxt10;
    private javax.swing.JLabel jtxt11;
    private javax.swing.JLabel jtxt12;
    private javax.swing.JLabel jtxt13;
    private javax.swing.JLabel jtxt14;
    private javax.swing.JLabel jtxt15;
    private javax.swing.JLabel jtxt16;
    private javax.swing.JLabel jtxt18;
    private javax.swing.JLabel jtxt19;
    private javax.swing.JLabel jtxt2;
    private javax.swing.JLabel jtxt20;
    private javax.swing.JLabel jtxt22;
    private javax.swing.JLabel jtxt23;
    private javax.swing.JLabel jtxt24;
    private javax.swing.JLabel jtxt25;
    private javax.swing.JLabel jtxt26;
    private javax.swing.JLabel jtxt27;
    private javax.swing.JLabel jtxt28;
    private javax.swing.JLabel jtxt29;
    private javax.swing.JLabel jtxt3;
    private javax.swing.JLabel jtxt30;
    private javax.swing.JLabel jtxt31;
    private javax.swing.JLabel jtxt32;
    private javax.swing.JLabel jtxt33;
    private javax.swing.JLabel jtxt34;
    private javax.swing.JLabel jtxt35;
    private javax.swing.JLabel jtxt36;
    private javax.swing.JLabel jtxt4;
    private javax.swing.JLabel jtxt5;
    private javax.swing.JLabel jtxt6;
    private javax.swing.JLabel jtxt7;
    private javax.swing.JLabel jtxt8;
    private javax.swing.JLabel jtxt9;
    private javax.swing.JMenuItem printRecord;
    private javax.swing.JMenu tuychon;
    // End of variables declaration//GEN-END:variables
private int printRecord(JPanel panel){
        
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D graphics2D =(Graphics2D)graphics;
                
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                
                graphics2D.scale(0.5,0.5);
                
                panel.print(graphics2D);
                
                return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        int t=0;
        if(returningResult){
            try{
                printerJob.print();
                return t=1;
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "In Lỗi :" + printerException.getLocalizedMessage());
            }
        }
        return t;
    }
}
